language: minimal
services:
  - docker
before_install:
  - $TRAVIS_BUILD_DIR/support/docker_pull_oracle.sh
  - $TRAVIS_BUILD_DIR/support/start_oracle_as_daemon.sh
  - sleep 45
script:
  - $TRAVIS_BUILD_DIR/tests/instance_is_available.sh
